Bumped nixpkgs, fakedir, added command dep checking

diff --git a/builder/nixie/output/nix-wrapped.sh.in b/builder/nixie/output/nix-wrapped.sh.in
--- a/builder/nixie/output/nix-wrapped.sh.in
+++ b/builder/nixie/output/nix-wrapped.sh.in
@@ -86,6 +86,27 @@ _untar() {
   } | tar -x "$@"
 }
 
+# Check that a command is available, and if not, add it to the list of missing
+# commands to print at the end
+declare -a MISSING_CMDS
+_avail() {
+  which -p $1 >&/dev/null || MISSING_CMDS+="$1"
+}
+
+# Print the list of missing commands and return 1, if any commands are missing
+_avail_end() {
+  if ((${#MISSING_CMDS[@]}))
+  then
+    tput rmcup
+    >&2 echo "ERROR: The following commands are missing:"
+    >&2 echo "$MISSING_CMDS"
+    >&2 echo "Use your distribution's package manager to install them, then try again."
+    return 1
+  else
+    return 0
+  fi
+}
+
 # Best-attempt script for downloading files. We first try wget, then cURL,
 # then Python 3.
 _dl() {
@@ -239,6 +260,14 @@ _find_or_build_boost () {
 _try_build_nix() {
   source_root="$REPO_ROOT/.nixie/sources"
   mkdir -p $source_root
+
+  _avail cc
+  _avail pkg-config
+  _avail make
+  _avail flex
+  _avail bison
+  _avail perl
+  _avail_end || return 1;
 
   _find_or_build_openssl
   _find_or_build_boost
@@ -406,6 +435,13 @@ _catch_nixie_args() {
 
 
 ##### ENTRY POINT #####
+
+# Check for required commands
+_avail tar
+_avail gzip
+_avail uname
+_avail kill
+_avail_end || exit 1
 
 # Load feature attributes of our resource tarball
 eval "$(_untar -O features || _bail "The resource archive is missing or malformed.")"
